DO_AN_LAP_TRINH_WEB/Controllers/NguoiDungController.cs
using DO_AN_LAP_TRINH_WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;

namespace DO_AN_LAP_TRINH_WEB.Controllers
{
    public class NguoiDungController : Controller
    {
        // GET: NguoiDung
        MyDataDataContext data = new MyDataDataContext();
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangKy(System.Web.Mvc.FormCollection collection, KhachHang kh)
        {
            try
            {
                var hoten = collection["hoten"];
                var tendangnhap = collection["tendangnhap"];
                var matkhau = collection["matkhau"];
                var MatKhauXacNhan = collection["MatKhauXacNhan"];
                var email = collection["email"];
                var diachi = collection["diachi"];
                var dienthoai = collection["dienthoai"];
                var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["ngaysinh"]);
                if (String.IsNullOrEmpty(MatKhauXacNhan))
                {
                    ViewData["NhapMKXN"] = "Phải nhập mật khẩu xác nhận!";
                }
                else
                {
                    if (!matkhau.Equals(MatKhauXacNhan))
                    {
                        ViewData["MatKhauGiongNhau"] = "Mật khẩu và mật khẩu xác nhận phải giống nhau";
                    }
                    else
                    {
                        kh.hoten = hoten;
                        kh.tendangnhap = tendangnhap;
                        kh.matkhau = matkhau;
                        kh.email = email;
                        kh.diachi = diachi;
                        kh.dienthoai = dienthoai;
                        DateTime temp;
                        bool flag = DateTime.TryParse(ngaysinh, out temp);
                        if (flag == true)
                            kh.ngaysinh = temp;
                        data.KhachHangs.InsertOnSubmit(kh);
                        data.SubmitChanges();
                        return RedirectToAction("DangNhap");
                    }
                }
            }
            catch (Exception e)
            {
                MessageBox.Show(e.StackTrace);

            }
            return this.DangKy();
        }
        [HttpGet]
        public ActionResult DangNhap()
        {
            return View();
        }
        [HttpPost]
        public ActionResult DangNhap(System.Web.Mvc.FormCollection collection)
        {
            var tendangnhap = collection["tendangnhap"];
            var matkhau = collection["matkhau"];
            KhachHang kh = data.KhachHangs.SingleOrDefault(n => n.tendangnhap == tendangnhap && n.matkhau == matkhau);
            if (kh != null)
            {
                ViewBag.ThongBao = "Chúc mừng đăng nhập thành công";
                Session["TaiKhoan"] = kh;
            }
            else
            {
                ViewBag.ThongBao = "Tên đăng nhập hoặc mật khẩu không đúng";
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

DO_AN_LAP_TRINH_WEB/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DO_AN_LAP_TRINH_WEB.Models;
using PagedList;

namespace DO_AN_LAP_TRINH_WEB.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        MyDataDataContext data = new MyDataDataContext();
        public ActionResult ListSanPham()
        {
            KhachHang kh = (KhachHang)Session["TaiKhoan"];
            var all_sanpham = from ss in data.SanPhams select ss;
            //return View(all_sanpham);
            if (Session["TaiKhoan"] == null)
            {
                return RedirectToAction("XacNhanAdmin", "GioHang");
            }
            else
            {
                if (kh.admin == 1)
                {

                    return View(all_sanpham);
                }
                else
                {
                    return RedirectToAction("DaXacNhanAdmin", "GioHang");
                }
            }
        }
        public ActionResult Details(int id)
        {
            var D_sanpham = data.SanPhams.Where(m => m.maSP == id).First();
            return View(D_sanpham);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(FormCollection collection, SanPham s)
        {
            var E_ten = collection["tenSP"];
            var E_mota = collection["mota"];
            var E_gia = Convert.ToDecimal(collection["giaban"]);
            var E_hinh = collection["hinh"];
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_soluongton = Convert.ToInt32(collection["soluongton"]);
            if (string.IsNullOrEmpty(E_ten))
            {
                ViewData["Error"] = "Don't empty!";
            }

            else
            { 
                s.tenSP = E_ten.ToString();
                s.hinh = E_hinh.ToString();
                s.giaban = E_gia;
                s.ngaycapnhat = E_ngaycapnhat;
                s.soluongton = E_soluongton;
                data.SanPhams.InsertOnSubmit(s);
                data.SubmitChanges();
                return RedirectToAction("ListSanPham");
            }
            return this.Create();
        }

        public string ProcessUpload(HttpPostedFileBase file)
        {
            if (file == null)
            {
                return "";
            }
            file.SaveAs(Server.MapPath("~/Content/images/" + file.FileName));
            return "/Content/images/" + file.FileName;
        }

        public ActionResult Edit(int id)
        {
            var E_sach = data.SanPhams.First(m => m.maSP == id);
            return View(E_sach);
        }
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var E_sach = data.SanPhams.First(m => m.maSP == id);
            var E_ten = collection["tenSP"];
            var E_mota = collection["mota"];
            var E_gia = Convert.ToDecimal(collection["giaban"]);
            var E_hinh = collection["hinh"];
            var E_ngaycapnhat = Convert.ToDateTime(collection["ngaycapnhat"]);
            var E_soluongton = Convert.ToInt32(collection[" soluongton"]);
            if (string.IsNullOrEmpty(E_ten))
            {
                ViewData["Error"] = "Don 't empty!";
            }
            else
            {
                E_sach.tenSP = E_ten;
                E_sach.hinh = E_hinh;
                E_sach.giaban = E_gia;
                E_sach.ngaycapnhat = E_ngaycapnhat;
                E_sach.soluongton = E_soluongton;
                UpdateModel(E_sach);
                data.SubmitChanges();
                return RedirectToAction("ListSanPham");
            }
            return this.Edit(id);
        }
        public ActionResult Delete(int id)
        {
            var D_sach = data.SanPhams.First(m => m.maSP == id);
            return View(D_sach);
        }
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var D_sach = data.SanPhams.Where(m => m.maSP == id).First();
            data.SanPhams.DeleteOnSubmit(D_sach);
            data.SubmitChanges();
            return RedirectToAction("ListSanPham");
        }

    }
}

DO_AN_LAP_TRINH_WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("ADMIN", "ListSanPham", "SanPham")</li>
                    <li>@Html.ActionLink("SẢN PHẨM", "Index", "Home")</li>
                    <li>@Html.Partial("~/Views/GioHang/GioHangPartial.cshtml")</li>
                    
                </ul>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav text-end">
                        <li>@Html.ActionLink("Đăng Ký", "DangKy", "NguoiDung")</li>
                        <li>@Html.ActionLink("Đăng Nhập", "DangNhap", "NguoiDung")</li>
                    </ul>
                </div>
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - DESGIN BY NHOM 9 </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @RenderSection("upload", required: false)
</body>
</html>